[tox]
env_list = lint, 3.9, 3.1{0, 1, 2, 3}

[testenv]
deps =
    pytest
    -r requirements.txt
commands = pytest -W ignore::UserWarning -W ignore::DeprecationWarning

[testenv:lint]
description = run linters
skip_install = true
deps =
    black
commands = black {posargs:.}
